### ISSUE TITLE
Development workflow inconsistency

### ISSUE THREAD

**Issue by hemberger** [MechanicalSoup/MechanicalSoup#100]
If we run `python setup.py test`, then the tests are run in the working tree of the repository. However, if we simply run `pytest`, then the tests are run against the installed version of the module, which may be different than the one that is currently in the working tree.

Advantages of `python setup.py test`:
* You are guaranteed to be testing the code as it currently exists. It is all too easy to make a breaking change to the working tree, run `pytest` (forgetting to `python setup.py install` first), have the tests pass and assume that your change is correct.
* The files reported by `pytest-cov` are much more readable. For example, you'll simply see `mechanicalsoup/browser.py` instead of `.virtual-py3/lib/python3.5/site-packages/MechanicalSoup-0.8.0-py3.5.egg/mechanicalsoup/browser.py`.
* Dependencies (except for `flake8`) do not need to be installed manually, vastly simplifying the development instructions... so long as you are okay with a bunch of egg-related cruft that is output before the tests, e.g. for each dependency you get:
```
Using /repos/MechanicalSoup/.eggs/requests-2.18.4-py3.5.egg
Searching for certifi>=2017.4.17
Best match: certifi 2017.7.27.1
Processing certifi-2017.7.27.1-py3.5.egg
```

Disadvantages of `python setup.py test`:
* Since `test` is aliased to `pytest`, it is not possible to pass arguments to `pytest` without modifying `setup.cfg` (that I'm aware of).

I don't know what the standard way of doing this is (I suspect this is why a lot of people use tools like `tox` to manage their build/dev environments). All I know is that the two methods are currently inconsistent, and that's dangerous. In my opinion, the benefits of `python setup.py test` make it preferable, but I don't think either option is ideal (or if we could even enforce that one is used if we wanted to).

**Comment by moy** [comment]
There's a 3rd option that you didn't mention: running individual scripts like `cd tests && python ./test_$whatever.py`, which does essentially what `pytest` does, but for individual test files (not a coincidence, it does call pytest underneath).

I personally prefer always testing the working directory, not the installed version. Essentially for the reasons you mention, but also because it's simpler (no need for virtualenv, no risk of polluting installed libs with a broken one, ...).

It is relatively simple to unify everything by adding `../mechanicalsoup` to `sys.path` in the test scripts. I can do that if there's a consensus that it's a good idea. Opinions from others are welcome, in particular what is the most "pythonish" way of doing this.

**Comment by hemberger** [comment]
I like your idea of adding the working tree to the test path, because it does solve the problem in a simple way. However, I also don't know if it's the most pythonic solution, so hopefully someone more experienced can comment.

**Comment by moy** [comment]
Pushed a PR that should do the trick. Second pair of eyes welcome.
