### ISSUE TITLE
Allow passing a Tag object to StatefulBrowser.select_form

### ISSUE THREAD

**Issue by sbraz** [MechanicalSoup/MechanicalSoup#169]
Hi,
I've recently had to select a form based on its children and the only way I found to do that is:
```py
buttons = browser.get_current_page().select("form > button[name=apply]")
browser._StatefulBrowser__current_form = mechanicalsoup.Form(buttons[0].parent)
browser.submit_selected()
```
Could you consider adding something like `if isinstance(selector, bs4.element.Tag): …` to `select_form` ?

**Comment by moy** [comment]
That sounds like a possible improvement yes. I won't have time to add it before a while, but pull-requests are welcome (that should be an easy one hopefully ;-) ).

**Comment by krlk89** [comment]
I thought this was a good issue to get my foot in the door in contributing to MechanicalSoup and so I looked into it.

I'm not quite sure what OP meant with "allow passing a Tag object" because form is also a html tag.
I guess the intent was to pass some other tag (or id or class) and then search the parent(s) of that for the form (and if a form is not found, then raise a LinkNotFoundError).

I hope to do a pull request sometime this week, but if I have misunderstood the premise of this feature request then please let me know.

**Comment by moy** [comment]
The feature requested here is simpler than you seem to think. Currently, `select_form` accept only a string as argument, and searches for the corresponding Tag object. This issue is about accepting a Tag object directly. The Tag object would be the form tag, not its children.

**Comment by sbraz** [comment]
@krlk89 In some cases I can't just use a selector to find the right form. In this example, I chose the form based on one of its inputs.

**Comment by krlk89** [comment]
@moy Aha, that makes sense! I will still try to implement this feature this week.
@sbraz Got it!

**Comment by krlk89** [comment]
I have now created a pull request which addresses this issue.
