### ISSUE TITLE
Scraping AWS hosted file

### ISSUE THREAD

**Issue by jrobinson-uk** [MechanicalSoup/MechanicalSoup#206]
I'm trying to scrape some CSV data from a site which in turn hosts the data in AWS, upon trying to download I get a linkNotFoundError:

So far I am able to log into site:
```python
import mechanicalsoup
b = mechanicalsoup.StatefulBrowser(soup_config={'features':
'lxml'},raise_on_404=False,user_agent='Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',)
b.open("https://www.<site>.com/sign-in")
b.select_form('form[action="/sign-in"]')


b["email"] = "xxxx"
b["password"] = "xxxxxx"
response = b.submit_selected()

b.open("page holding links to csv")
print(b.links())

b.download_link(link="https://www.site.com/path/to/some/download/without/filename/)
```

Replicating in browser it looks like the file is coming from AWS, but the `download_link` call doesn't seem to follow the url to the actual download.

Is this possible or is AWS going to prevent it?

**Comment by jrobinson-uk** [comment]
The URL i'm trying to download the csv from is `www.sitename.com/admin/some_long_path/survey_responses`

The link doesn't contain the actual filename and presumably redirects me somehow. When I click on it in my browser I get a csv download.

**Comment by moy** [comment]
I think you're mis-using `download_link`. The argument is a regex, to be matched against URLs available in the page. If you're getting a `LinkNotFound`, it means the *link* was not found in the page (this is just a search in the current page's text, no access to the remote site). If you already know the exact URL, then using a plain `.open()` should be easier. Otherwise, you have to make sure that 1) the link is present in the current page, and 2) you didn't mess up with regexp special characters.

**Comment by jrobinson-uk** [comment]
Ahhh I see, yes I can open the link, that worked. How do I access the csv file?

**Comment by jrobinson-uk** [comment]
Actually, got it

**Comment by hemberger** [comment]
The `download_link` method would probably be more self-evident if there was also a `download` method that just saved the contents of a URL to file. I'm not sure if it should be MechanicalSoup's job to implement such a function, but if you think it should, let us know!
