### ISSUE TITLE
Error when selecting the only form on a page

### ISSUE THREAD

**Issue by Hunterfollow123** [MechanicalSoup/MechanicalSoup#344]
Hi,

According to the docs when there's only one form you can use `select_form()` without arguments
but `mechanicalsoup.utils.LinkNotFoundError` came up,

I also tried specifying arguments but the form confused me
here's the form I'm working with : 

`<form class="authBoxExpanded-2jqaBe authBox-hW6HRx theme-dark"><div class="centeringWrapper-2Rs1dR">`

I'm kinda new to programming so excuse me if this question is stupid or not worth an issue!

**Comment by hemberger** [comment]
Hi, and welcome!

Unfortunately, based on the snippet of HTML you provided, it looks like your page may be using javascript for form submission, in which case MechanicalSoup might not be the right tool for the job (because it doesn't support javascript).

Please see https://mechanicalsoup.readthedocs.io/en/stable/faq.html#form-submission-has-no-effect-or-fails for more details.

**Comment by Hunterfollow123** [comment]
Okay i think I read before that it doesn't support javascript... well that confirms it, that won't stop me tho from using such a great tool.
Thank you for responding!
