### ISSUE TITLE
Any plans on making the package fully html5-compliant?

### ISSUE THREAD

**Issue by caffeinatedMike** [MechanicalSoup/MechanicalSoup#417]
#380 mentions briefly about the incomplete HTML5 compliance and since mechanize has re-animated a bit it appears to have adjusted their codebase to be html5 compliant (I could be wrong, please correct me if I am). So, I just wanted to see if this brain child of its parent project would follow suit. I understand there's a small team maintaining this project now, you guys have created exactly what I was looking for in a key piece of a new project of mine and the interface is perfect for my idea! I just want to make sure I don't get too deep into development before I hit a snag with the html5 shortcomings.

**Comment by hemberger** [comment]
Hi, I'm glad to hear you've found MechanicalSoup to be useful! I can't speak for the other maintainers, but I personally don't have any intention of proactively adding full HTML5 support at this time, simply because there's so much in the spec. That said, I'll make sure to find time to address any specific HTML5 issues that are reported, and of course we're always happy to review PRs. I hope that provides some peace of mind if you decide to use MechanicalSoup.

**Comment by caffeinatedMike** [comment]
Completely understandable and it does, thank you! I'll be sure to report any issues I find and would be happy to propose solutions to them if I'm able.
