### ISSUE TITLE
Tutorials or documentation?

### ISSUE THREAD

**Issue by DedrichVonDorn** [MechanicalSoup/MechanicalSoup#6]
Are there any tutorials or documentation available for this? Something a bit more robust than the example of logging into GitHub?

**Comment by halhx** [comment]
Form Submission isn't good. I've just forked and will make some improvements there. Do you have a process for contributing code back?

**Comment by scarrick68** [comment]
Commenting to bring this back up. More in depth form example with submissions on consecutive pages,  filling in select field (i mean <select> elements), how to press a button on a page would all be very helpful.

**Comment by scarrick68** [comment]
The github example on the home page is unclear. I'm assuming this section

# verify we are now logged in
messages = page2.soup.find('div', class_='flash-messages')
if messages:
    print(messages.text)
assert page2.soup.select(".logout-form")

Checks for a div with that class which should only be present after log in. However, there is no div with class='flash-messages' on the login page or after being logged in. I checked in Chrome's console. the assert statement also didn't print anything when I ran the example.

print(page2.soup.title.text)

just prints "Github"

**Comment by moy** [comment]
I have some pieces of code using MechanicalSoup here: https://gitlab.com/chamilotools/chamilotools if anyone wants example. I think a "Projects using MechanicalSoup" section could be added to the README of MechanicalSoup so that people looking for examples can find more.

I implemented a [helper to simplify the final code](https://gitlab.com/chamilotools/chamilotools/blob/master/chamilolib/chamiloBrowser.py), I'll try to contribute it here when I get time.

**Comment by eoghanmurray** [comment]
And another example (unfortunately an account is needed to see it in action, but might be useful as an example of a login/download/unzip-files pattern):
https://github.com/GoPixie/rdg-to-db/blob/master/download

**Comment by moy** [comment]
OK, there's now a tutorial on http://mechanicalsoup.readthedocs.io/en/latest/, and there's a separate issue at #114 to track remaining missing docs.
